FROM node:10

WORKDIR /usr/src/app

# CO/#PY ./server .

# RUN npm install

#RUN apt-get update
#RUN apt-get install

# install application
# RUN yarn install

# add source
CMD ["node", "index.js"]

EXPOSE 3000

# COPY ./client .
# RUN npm install
