FROM node:10

WORKDIR /usr/src/app

# CO/#PY ./server .

# RUN npm install

#RUN apt-get update
#RUN apt-get install

# install application
# RUN yarn install

# add source
CMD ["npm", "start"]

EXPOSE 4000
EXPOSE 9229

# COPY ./client .
# RUN npm install
